Repository Ferrite-FEM/Ferrite.jl, pull requests merged in 2023-05, with the labels that each got.

#695 Default to `Lagrange{refdim,refshape,1}()` for geometric mapping
  docs/src/literate/incompressible_elasticity.jl
  docs/src/literate/ns_vs_diffeq.jl
  docs/src/literate/plasticity.jl
  docs/src/literate/quasi_incompressible_hyperelasticity.jl
  docs/src/literate/stokes-flow.jl
  docs/src/literate/topology_optimization.jl
  src/FEValues/cell_values.jl
  src/FEValues/face_values.jl
  test/test_cellvalues.jl
  test/test_facevalues.jl
Labels: needs changelog

#697 Remove deprecated L2Projector methods
  src/L2_projection.jl
  test/test_l2_projection.jl
Labels: needs changelog

#698 Deprecate `function_*(::VectorValues, ::Int, ::VectorDofs)`
  src/FEValues/common_values.jl
  src/deprecations.jl
  test/test_cellvalues.jl
  test/test_facevalues.jl
Labels: needs changelog

#699 Remove `project_to_nodes` option in L2 projection
  docs/src/literate/computational_homogenization.jl
  docs/src/literate/postprocessing.jl
  src/Dofs/apply_analytical.jl
  src/L2_projection.jl
  test/test_l2_projection.jl
  test/test_pointevaluation.jl
Labels: needs changelog, deprecation

#700 Deprecate `compute_vertex_values`
  docs/src/reference/grid.md
  src/Grid/grid.jl
  src/deprecations.jl
  src/exports.jl
  test/test_grid_dofhandler_vtk.jl
  test/test_l2_projection.jl
Labels: deprecation

#708 Merge (Cell|Face)(Scalar|Vector)Values
  docs/src/literate/computational_homogenization.jl
  docs/src/literate/heat_equation.jl
  docs/src/literate/helmholtz.jl
  docs/src/literate/hyperelasticity.jl
  docs/src/literate/incompressible_elasticity.jl
  docs/src/literate/landau.jl
  docs/src/literate/linear_shell.jl
  docs/src/literate/ns_vs_diffeq.jl
  docs/src/literate/plasticity.jl
  docs/src/literate/postprocessing.jl
  docs/src/literate/quasi_incompressible_hyperelasticity.jl
  docs/src/literate/stokes-flow.jl
  docs/src/literate/threaded_assembly.jl
  docs/src/literate/topology_optimization.jl
  docs/src/literate/transient_heat_equation.jl
  src/Dofs/DofHandler.jl
  src/Dofs/apply_analytical.jl
  src/FEValues/cell_values.jl
  src/FEValues/common_values.jl
  src/FEValues/face_integrals.jl
  src/FEValues/face_values.jl
  src/Ferrite.jl
  src/L2_projection.jl
  src/PointEval/PointEvalHandler.jl
  src/PointEval/point_values.jl
  src/deprecations.jl
  src/exports.jl
  test/test_abstractgrid.jl
  test/test_apply_rhs.jl
  test/test_cellvalues.jl
  test/test_constraints.jl
  test/test_deprecations.jl
  test/test_facevalues.jl
  test/test_grid_dofhandler_vtk.jl
  test/test_l2_projection.jl
  test/test_mixeddofhandler.jl
  test/test_pointevaluation.jl
Labels: needs changelog

#716 `QuadratureRule`: remove `dim` parameter and introduce `FaceQuadratureRule`
  docs/src/literate/computational_homogenization.jl
  docs/src/literate/heat_equation.jl
  docs/src/literate/helmholtz.jl
  docs/src/literate/hyperelasticity.jl
  docs/src/literate/incompressible_elasticity.jl
  docs/src/literate/landau.jl
  docs/src/literate/linear_shell.jl
  docs/src/literate/ns_vs_diffeq.jl
  docs/src/literate/plasticity.jl
  docs/src/literate/quasi_incompressible_hyperelasticity.jl
  docs/src/literate/stokes-flow.jl
  docs/src/literate/threaded_assembly.jl
  docs/src/literate/topology_optimization.jl
  docs/src/literate/transient_heat_equation.jl
  docs/src/reference/fevalues.md
  docs/src/reference/quadrature.md
  src/Dofs/DofHandler.jl
  src/Dofs/apply_analytical.jl
  src/FEValues/cell_values.jl
  src/FEValues/common_values.jl
  src/FEValues/face_integrals.jl
  src/FEValues/face_values.jl
  src/L2_projection.jl
  src/PointEval/point_values.jl
  src/Quadrature/quadrature.jl
  src/deprecations.jl
  src/exports.jl
  test/test_abstractgrid.jl
  test/test_apply_rhs.jl
  test/test_cellvalues.jl
  test/test_constraints.jl
  test/test_deprecations.jl
  test/test_facevalues.jl
  test/test_grid_dofhandler_vtk.jl
  test/test_l2_projection.jl
  test/test_mixeddofhandler.jl
  test/test_pointevaluation.jl
  test/test_quadrules.jl
Labels: needs changelog

#719 Allocate less in `find_local_coordinate`
  src/PointEval/PointEvalHandler.jl
Labels: optimization

#721 Fold `Ferrite.value` into methods of `shape_value`
  src/FEValues/cell_values.jl
  src/FEValues/face_values.jl
  src/PointEval/PointEvalHandler.jl
  src/PointEval/point_values.jl
  src/deprecations.jl
  src/interpolations.jl
  test/test_deprecations.jl
  test/test_interpolations.jl
Labels: enhancement, needs changelog, deprecation

#730 `CellIterator` broadcast safety doc warning
  src/iterators.jl
Labels: docs
