Repository Ferrite-FEM/Ferrite.jl, pull requests merged in 2023-12, with the labels that each got.

#743 `InterfaceValues` for DG interface integration
  Project.toml
  benchmark/benchmarks-assembly.jl
  benchmark/helper.jl
  docs/src/devdocs/elements.md
  docs/src/devdocs/interpolations.md
  docs/src/reference/fevalues.md
  src/FEValues/common_values.jl
  src/FEValues/face_integrals.jl
  src/FEValues/interface_values.jl
  src/Ferrite.jl
  src/Grid/grid.jl
  src/exports.jl
  src/iterators.jl
  test/runtests.jl
  test/test_grid_dofhandler_vtk.jl
  test/test_interfacevalues.jl
  test/test_interpolations.jl
  test/test_utils.jl
Labels: feature, gsoc23, awaiting review

#792 Improvements to assembler
  src/assembler.jl
  test/test_assemble.jl
Labels: awaiting review

#764 Split values into geometric mapping and function values
  benchmark/helper.jl
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/src/assets/references.bib
  docs/src/devdocs/FEValues.md
  docs/src/devdocs/index.md
  docs/src/devdocs/interpolations.md
  docs/src/literate-howto/postprocessing.jl
  docs/src/literate-tutorials/incompressible_elasticity.jl
  docs/src/literate-tutorials/linear_shell.jl
  docs/src/reference/fevalues.md
  docs/src/topics/FEValues.md
  docs/src/topics/SimpleCellValues_literate.jl
  src/Dofs/DofHandler.jl
  src/FEValues/FunctionValues.jl
  src/FEValues/GeometryMapping.jl
  src/FEValues/cell_values.jl
  src/FEValues/common_values.jl
  src/FEValues/face_integrals.jl
  src/FEValues/face_values.jl
  src/FEValues/interface_values.jl
  src/Ferrite.jl
  src/PointEval/PointEvalHandler.jl
  src/PointEval/point_values.jl
  src/deprecations.jl
  src/interpolations.jl
  test/test_cellvalues.jl
  test/test_facevalues.jl
  test/test_interfacevalues.jl
Labels: awaiting review

#759 FaceSkeleton Vroom 1
  src/Grid/topology.jl
  test/test_grid_dofhandler_vtk.jl
Labels: enhancement, gsoc23, awaiting review

#855 Update benchmarks
  benchmark/benchmarks-assembly.jl
  benchmark/helper.jl
Labels: awaiting review

#802 More flexibility for internal types
  Project.toml
  src/Dofs/ConstraintHandler.jl
  src/FEValues/FaceValues.jl
  src/FEValues/PointValues.jl
  src/assembler.jl
  src/interpolations.jl
  src/iterators.jl
  test/runtests.jl
  test/test_cellvalues.jl
  test/test_dofs.jl
  test/test_interpolations.jl
Labels: awaiting review

#860 Make close of ConstraintHandler 50x faster
  src/Dofs/ConstraintHandler.jl
Labels: performance
