Repository Ferrite-FEM/Ferrite.jl, pull requests merged in 2024-09, with the labels that each got.

#916 Generalize CSC assembler
  docs/src/devdocs/assembly.md
  docs/src/devdocs/index.md
  docs/src/literate-howto/threaded_assembly.jl
  ext/FerriteBlockArrays.jl
  src/Ferrite.jl
  src/assembler.jl
Labels: needs changelog, awaiting review

#1064 Replace `sparse` with `spzeros!` in grid coloring
  src/Grid/coloring.jl
Labels: performance

#1069 Consistently return the vtk file in export methods
  src/Export/VTK.jl
  test/test_grid_dofhandler_vtk.jl
  test/test_vtk_export.jl
Labels: visualization

#1068 Modernize the threaded assembly howto
  Project.toml
  docs/Manifest.toml
  docs/Project.toml
  docs/src/literate-howto/threaded_assembly.jl
  test/test_examples.jl
Labels: docs
