Repository Ferrite-FEM/Ferrite.jl, pull requests merged in 2024-05, with the labels that each got.

#692 Abstraction layer around vtk export
  CHANGELOG.md
  docs/src/literate-gallery/helmholtz.jl
  docs/src/literate-gallery/landau.jl
  docs/src/literate-gallery/quasi_incompressible_hyperelasticity.jl
  docs/src/literate-gallery/topology_optimization.jl
  docs/src/literate-howto/postprocessing.jl
  docs/src/literate-howto/threaded_assembly.jl
  docs/src/literate-tutorials/computational_homogenization.jl
  docs/src/literate-tutorials/dg_heat_equation.jl
  docs/src/literate-tutorials/heat_equation.jl
  docs/src/literate-tutorials/hyperelasticity.jl
  docs/src/literate-tutorials/incompressible_elasticity.jl
  docs/src/literate-tutorials/linear_shell.jl
  docs/src/literate-tutorials/ns_vs_diffeq.jl
  docs/src/literate-tutorials/plasticity.jl
  docs/src/literate-tutorials/porous_media.jl
  docs/src/literate-tutorials/stokes-flow.jl
  docs/src/literate-tutorials/transient_heat_equation.jl
  docs/src/reference/export.md
  docs/src/topics/export.md
  src/Dofs/ConstraintHandler.jl
  src/Export/VTK.jl
  src/Ferrite.jl
  src/Grid/coloring.jl
  src/L2_projection.jl
  src/deprecations.jl
  src/exports.jl
  test/runtests.jl
  test/test_constraints.jl
  test/test_deprecations.jl
  test/test_grid_dofhandler_vtk.jl
  test/test_l2_projection.jl
  test/test_mixeddofhandler.jl
  test/test_vtk_export.jl
Labels: awaiting review

#929 Remove workaround for facets in porous media example
  docs/Manifest.toml
  docs/src/literate-tutorials/porous_media.jl
Labels: awaiting review

#954 Run ExplicitImport.jl's checks on CI
  .github/workflows/Check.yml
  .github/workflows/lint.yml
  src/Export/VTK.jl
  src/Ferrite.jl
Labels: CI

#715 Embedded elements showcase: Gray-Scott model on a sphere
  docs/Manifest.toml
  docs/download_resources.jl
  docs/make.jl
  docs/src/literate-tutorials/reactive_surface.jl
  docs/src/tutorials/index.md
Labels: docs, awaiting review
